In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent=dataset[["charges"]]

In [10]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostRegressor
param_grid= {'n_estimators':[10,50,100,1000]}

grid=GridSearchCV(AdaBoostRegressor(),param_grid, refit=True, verbose=3,n_jobs=-1)
    
grid.fit(independent,dependent)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=AdaBoostRegressor(), n_jobs=-1,
             param_grid={'n_estimators': [10, 50, 100, 1000]}, verbose=3)

In [13]:
#best parameter after tuning:
re=grid.cv_results_

print("The R_score for best parameter is={}".format(grid.best_params_))

The R_score for best parameter is={'n_estimators': 1000}

In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.043150,0.004811,0.005131,0.000403,10,{'n_estimators': 10},0.847767,0.766696,0.849398,0.799002,0.836016,0.819776,0.032168,3
1,0.038926,0.003056,0.005680,0.001412,50,{'n_estimators': 50},0.843729,0.782891,0.833698,0.812518,0.835085,0.821584,0.021903,2
2,0.044890,0.010374,0.004933,0.000336,100,{'n_estimators': 100},0.839177,0.764689,0.848862,0.811944,0.812607,0.815456,0.029245,4
3,0.033090,0.005215,0.003955,0.000698,1000,{'n_estimators': 1000},0.846484,0.777991,0.860337,0.801709,0.834854,0.824275,0.030190,1

In [16]:
age_input=float(input("Enter the age:"))
bmi_input=float(input("Enter the bmi:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
children_input=int(input("Enter the children:"))
smoker_yes_input=int(input("smoker yes 0 or 1"))

Enter the age: 56
Enter the bmi: 87
Sex Male 0 or 1: 1
Enter the children: 3
smoker yes 0 or 1 0

In [17]:
Future_prediction=grid.predict([[age_input,bmi_input,sex_male_input,children_input,smoker_yes_input]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but AdaBoostRegressor was fitted with feature names
  warnings.warn(

In [18]:
print("Future prediction={}".format(Future_prediction))

Future prediction=[16982.96202251]