In [1]:
#import libraries
#pandas is a library and it contains the functions related to the database.
import  pandas as pd

In [2]:
#variablename = filename(classname).functionnamne(passing the saved csv file as arguments):
dataset=pd.read_csv("Salary_Data.csv")

In [3]:
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [4]:
#input and output split:
#newvariablename = dataset(variablename) in which we have the "YearsExperience" column.
independent=dataset[["YearsExperience"]]

In [5]:
#display independent variable:
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [6]:
#splitting the dependent variable/response variable/target variable:
dependent=dataset[["Salary"]]

In [7]:
#display dependent variable:
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [10]:
#splitting train and test sets:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent, dependent,test_size = 0.30,random_state=0)

In [11]:
#Model Creation: (first 2 lines are procedure/formula)
#fit function/method acts as a substitute here.(substitute values in formula)
# Here the model has learnt(learning some inputs and its respective outputs)
#Regressor is like save a copy here.
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [13]:
#checking weight(slope/interval between the given values in the dataset):
#coef_ = in this particular method/variable(already prewritten that we are calling now, coef has been calculated here)
weight= regressor.coef_
weight

array([[9360.26128619]])

In [14]:
#checking bias(Initial/minimum value):
bias = regressor.intercept_
bias

array([26777.3913412])

In [19]:
#Evaluating if the model has correctly learnt using R square:
#predict is in-built function.
y_pred= regressor.predict(X_test)

In [20]:
#r2_score compares between actual output and predicted output.
from sklearn.metrics import r2_score
r_score= r2_score(y_test,y_pred)

In [21]:
#as score is nearly 1,the model performed so well/learnt well.
r_score

0.9740993407213511

In [33]:
#Saving the model as it has performed well:
import pickle
filename="finalized_model_linear.sav"

In [34]:
#Here after executing, file is saved under 1.simple Linear Regression:(wb->write binary)
pickle.dump(regressor,open(filename,'wb'))

In [35]:
#Like giving a copy of the saved model to the end user to predict for other years of experience:
#read binary(read-only)
loaded_model=pickle.load(open(filename,'rb'))

In [28]:
#Giving input to predict dependent variable(salary):
result=loaded_model.predict([[15]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [29]:
#displaying result for 15 years of experience:
result

array([[167181.3106341]])