In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [10]:
dependent=dataset[["charges"]]

In [11]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['squared_error','absolute_error','poisson'],'n_estimators':[10,50,100]}

grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'n_estimators': [10, 50, 100]},
             verbose=3)

In [13]:
#print best parameters after tuning:
re=grid.cv_results_
re

{'mean_fit_time': array([0.0598423 , 0.27502689, 0.56315703, 0.3393075 , 1.43168836,
        2.78801785, 0.07021713, 0.32285199, 0.59937758]),
 'std_fit_time': array([0.00237761, 0.0060253 , 0.03585469, 0.039821  , 0.01200164,
        0.08201828, 0.00287341, 0.01405374, 0.05436061]),
 'mean_score_time': array([0.0055254 , 0.01168928, 0.01900606, 0.00541506, 0.01228108,
        0.01853151, 0.00554295, 0.01240125, 0.01830978]),
 'std_score_time': array([0.00042363, 0.00107406, 0.00198655, 0.0006356 , 0.00108434,
        0.00282317, 0.00046477, 0.0017051 , 0.00282063]),
 'param_criterion': masked_array(data=['squared_error', 'squared_error', 'squared_error',
                    'absolute_error', 'absolute_error', 'absolute_error',
                    'poisson', 'poisson', 'poisson'],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_estimators': masked_array(data=[10, 50, 100, 10, 50, 100, 10, 50, 100],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill_value=999999),
 'params': [{'criterion': 'squared_error', 'n_estimators': 10},
  {'criterion': 'squared_error', 'n_estimators': 50},
  {'criterion': 'squared_error', 'n_estimators': 100},
  {'criterion': 'absolute_error', 'n_estimators': 10},
  {'criterion': 'absolute_error', 'n_estimators': 50},
  {'criterion': 'absolute_error', 'n_estimators': 100},
  {'criterion': 'poisson', 'n_estimators': 10},
  {'criterion': 'poisson', 'n_estimators': 50},
  {'criterion': 'poisson', 'n_estimators': 100}],
 'split0_test_score': array([0.84504652, 0.84345337, 0.84692644, 0.81865752, 0.83375236,
        0.83679927, 0.83022886, 0.84612117, 0.85284469]),
 'split1_test_score': array([0.75091259, 0.77015257, 0.77494816, 0.77070947, 0.76275451,
        0.76559498, 0.77856314, 0.76961445, 0.77114908]),
 'split2_test_score': array([0.84921953, 0.85725307, 0.85758198, 0.83043542, 0.8462798 ,
        0.84889818, 0.83864162, 0.85627427, 0.85769558]),
 'split3_test_score': array([0.80530054, 0.81692237, 0.81632211, 0.82151079, 0.82277772,
        0.820998  , 0.80974405, 0.82115808, 0.81783688]),
 'split4_test_score': array([0.83507512, 0.83640704, 0.83574158, 0.82843243, 0.83240608,
        0.8392519 , 0.83113694, 0.84148637, 0.83898766]),
 'mean_test_score': array([0.81711086, 0.82483768, 0.82630405, 0.81394913, 0.81959409,
        0.82230847, 0.81766292, 0.82693087, 0.82770278]),
 'std_test_score': array([0.036485  , 0.03027958, 0.02908513, 0.02204804, 0.02938573,
        0.02973958, 0.0217764 , 0.0308534 , 0.03147916]),
 'rank_test_score': array([8, 4, 3, 9, 6, 5, 7, 2, 1], dtype=int32)}

In [16]:
print("The R_score for the best parameter is={}".format(grid.best_params_))

The R_score for the best parameter is={'criterion': 'poisson', 'n_estimators': 100}

In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.059842,0.002378,0.005525,0.000424,squared_error,10,"{'criterion': 'squared_error', 'n_estimators':...",0.845047,0.750913,0.849220,0.805301,0.835075,0.817111,0.036485,8
1,0.275027,0.006025,0.011689,0.001074,squared_error,50,"{'criterion': 'squared_error', 'n_estimators':...",0.843453,0.770153,0.857253,0.816922,0.836407,0.824838,0.030280,4
2,0.563157,0.035855,0.019006,0.001987,squared_error,100,"{'criterion': 'squared_error', 'n_estimators':...",0.846926,0.774948,0.857582,0.816322,0.835742,0.826304,0.029085,3
3,0.339307,0.039821,0.005415,0.000636,absolute_error,10,"{'criterion': 'absolute_error', 'n_estimators'...",0.818658,0.770709,0.830435,0.821511,0.828432,0.813949,0.022048,9
4,1.431688,0.012002,0.012281,0.001084,absolute_error,50,"{'criterion': 'absolute_error', 'n_estimators'...",0.833752,0.762755,0.846280,0.822778,0.832406,0.819594,0.029386,6
5,2.788018,0.082018,0.018532,0.002823,absolute_error,100,"{'criterion': 'absolute_error', 'n_estimators'...",0.836799,0.765595,0.848898,0.820998,0.839252,0.822308,0.029740,5
6,0.070217,0.002873,0.005543,0.000465,poisson,10,"{'criterion': 'poisson', 'n_estimators': 10}",0.830229,0.778563,0.838642,0.809744,0.831137,0.817663,0.021776,7
7,0.322852,0.014054,0.012401,0.001705,poisson,50,"{'criterion': 'poisson', 'n_estimators': 50}",0.846121,0.769614,0.856274,0.821158,0.841486,0.826931,0.030853,2
8,0.599378,0.054361,0.018310,0.002821,poisson,100,"{'criterion': 'poisson', 'n_estimators': 100}",0.852845,0.771149,0.857696,0.817837,0.838988,0.827703,0.031479,1

In [17]:
age_input=float(input("Enter the age:"))
bmi_input=float(input("Enter the bmi:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
children_input=int(input("Enter the children:"))
smoker_yes_input=int(input("smoker yes 0 or 1"))

Enter the age: 23
Enter the bmi: 89
Sex Male 0 or 1: 0
Enter the children: 5
smoker yes 0 or 1 1

In [19]:
Future_prediction=grid.predict([[age_input,bmi_input,sex_male_input,children_input,smoker_yes_input]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [22]:
print("Future prediction={}".format(Future_prediction))

Future prediction=[41616.382141]