In [1]:
import pandas as pd

In [15]:
dataset=pd.read_csv("insurance_pre.csv")

In [16]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [17]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [18]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [19]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [20]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [22]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [23]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [24]:
dependent=dataset[["charges"]]

In [25]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [28]:
#Gridsearch and Model Creation:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'kernel':['linear','poly','rbf','sigmoid'],'C':[10,100,1000,2000,3000]}

grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             verbose=3)

In [32]:
#print best parameter after tuning:
#print grid.best_params(best parameters from grid):
re=grid.cv_results_

print("The R_score value for best parameter{}:".format(grid.best_params_))

The R_score value for best parameter{'C': 1000, 'kernel': 'linear'}:

In [33]:
re

{'mean_fit_time': array([0.12554183, 0.09436626, 0.11185541, 0.12384067, 0.22124696,
        0.11859751, 0.13330536, 0.1393199 , 0.71243687, 0.12846723,
        0.12062736, 0.14837837, 1.11441207, 0.15102339, 0.12097807,
        0.13110552, 1.81065907, 0.16927814, 0.11915917, 0.12817516]),
 'std_fit_time': array([0.02150296, 0.00436275, 0.00458163, 0.00517672, 0.01231836,
        0.00714542, 0.01133481, 0.00479309, 0.08305341, 0.00579977,
        0.01511618, 0.01263333, 0.06396487, 0.01076534, 0.00418975,
        0.01399015, 0.28359007, 0.01289534, 0.00515914, 0.01377254]),
 'mean_score_time': array([0.01732111, 0.01770873, 0.05191364, 0.02903161, 0.01722083,
        0.01954341, 0.05862188, 0.02816582, 0.01756449, 0.0167181 ,
        0.05882974, 0.02807555, 0.01552072, 0.01606693, 0.04994316,
        0.02827377, 0.01128502, 0.01658115, 0.05387802, 0.02581806]),
 'std_score_time': array([0.00129938, 0.0012706 , 0.00269438, 0.00444331, 0.00122792,
        0.0028277 , 0.00592507, 0.00069078, 0.00108747, 0.00083352,
        0.00853457, 0.00172344, 0.00020369, 0.00040366, 0.00339608,
        0.00343524, 0.0030359 , 0.00051781, 0.00910383, 0.00136872]),
 'param_C': masked_array(data=[10, 10, 10, 10, 100, 100, 100, 100, 1000, 1000, 1000,
                    1000, 2000, 2000, 2000, 2000, 3000, 3000, 3000, 3000],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid', 'linear', 'poly', 'rbf', 'sigmoid',
                    'linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'sigmoid'},
  {'C': 100, 'kernel': 'linear'},
  {'C': 100, 'kernel': 'poly'},
  {'C': 100, 'kernel': 'rbf'},
  {'C': 100, 'kernel': 'sigmoid'},
  {'C': 1000, 'kernel': 'linear'},
  {'C': 1000, 'kernel': 'poly'},
  {'C': 1000, 'kernel': 'rbf'},
  {'C': 1000, 'kernel': 'sigmoid'},
  {'C': 2000, 'kernel': 'linear'},
  {'C': 2000, 'kernel': 'poly'},
  {'C': 2000, 'kernel': 'rbf'},
  {'C': 2000, 'kernel': 'sigmoid'},
  {'C': 3000, 'kernel': 'linear'},
  {'C': 3000, 'kernel': 'poly'},
  {'C': 3000, 'kernel': 'rbf'},
  {'C': 3000, 'kernel': 'sigmoid'}],
 'split0_test_score': array([ -0.0189429 ,  -0.12515269,  -0.11040913,  -0.11674324,
          0.55931297,  -0.13288461,  -0.16018172,  -0.14245497,
          0.7363985 ,  -0.0805268 ,  -0.15543029,  -2.04313994,
          0.68234915,  -0.02056724,  -0.1435097 ,  -7.20931696,
          0.67777829,   0.03769959,  -0.12895834, -15.56185339]),
 'split1_test_score': array([  0.02988647,  -0.08150541,  -0.09745886,  -0.11931157,
          0.52179776,  -0.08246084,  -0.10725311,  -0.16083065,
          0.6751618 ,  -0.02846903,  -0.09826656,  -2.68612062,
          0.63064161,   0.03568522,  -0.08759498,  -9.28294011,
          0.62681429,   0.0984962 ,  -0.07557819, -20.49890817]),
 'split2_test_score': array([ 2.21674226e-02, -1.11907046e-01, -7.44875522e-02, -8.52138486e-02,
         5.47690802e-01, -1.29219533e-01, -1.23430337e-01, -1.17544297e-01,
         6.80002381e-01, -7.33762368e-02, -1.23723557e-01, -2.19456334e+00,
         7.50713567e-01, -1.14680955e-02, -1.13312371e-01, -7.77657753e+00,
         7.32805738e-01,  4.92907957e-02, -1.00198784e-01, -1.70954740e+01]),
 'split3_test_score': array([ 3.11150946e-03, -1.31602268e-01, -9.95972567e-02, -1.08210107e-01,
         5.38804573e-01, -1.39961828e-01, -1.37753025e-01, -1.37983588e-01,
         6.99376769e-01, -8.66105151e-02, -1.37136880e-01, -2.21085823e+00,
         6.46367540e-01, -2.45873617e-02, -1.28590699e-01, -7.74507386e+00,
         6.33478783e-01,  3.56153439e-02, -1.16051182e-01, -1.67508766e+01]),
 'split4_test_score': array([ -0.06665348,  -0.17932768,  -0.12442819,  -0.10871636,
          0.50851762,  -0.1892193 ,  -0.20955111,  -0.13040193,
          0.67795161,  -0.13449284,  -0.20640524,  -1.94252105,
          0.72226093,  -0.07635973,  -0.19399153,  -6.89171908,
          0.69869163,  -0.02092444,  -0.17930409, -15.01216755]),
 'mean_test_score': array([-6.08619573e-03, -1.25899020e-01, -1.01276198e-01, -1.07639026e-01,
         5.35224744e-01, -1.34749222e-01, -1.47633859e-01, -1.37843088e-01,
         6.93778210e-01, -8.06950833e-02, -1.44192505e-01, -2.21544064e+00,
         6.86466559e-01, -1.94594410e-02, -1.33399856e-01, -7.78112551e+00,
         6.73913747e-01,  4.00354966e-02, -1.20018118e-01, -1.69838559e+01]),
 'std_test_score': array([0.03467157, 0.03179394, 0.01645872, 0.01202922, 0.01812189,
        0.03394787, 0.03551124, 0.01426274, 0.02295499, 0.03379451,
        0.036262  , 0.25540914, 0.04505602, 0.03569303, 0.03549164,
        0.82155661, 0.03987603, 0.03806422, 0.03457804, 1.91478335]),
 'rank_test_score': array([ 6, 12,  9, 10,  4, 14, 17, 15,  1,  8, 16, 18,  2,  7, 13, 19,  3,
         5, 11, 20], dtype=int32)}

In [34]:
table=pd.DataFrame.from_dict(re)

In [35]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.125542,0.021503,0.017321,0.001299,10,linear,"{'C': 10, 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,6
1,0.094366,0.004363,0.017709,0.001271,10,poly,"{'C': 10, 'kernel': 'poly'}",-0.125153,-0.081505,-0.111907,-0.131602,-0.179328,-0.125899,0.031794,12
2,0.111855,0.004582,0.051914,0.002694,10,rbf,"{'C': 10, 'kernel': 'rbf'}",-0.110409,-0.097459,-0.074488,-0.099597,-0.124428,-0.101276,0.016459,9
3,0.123841,0.005177,0.029032,0.004443,10,sigmoid,"{'C': 10, 'kernel': 'sigmoid'}",-0.116743,-0.119312,-0.085214,-0.108210,-0.108716,-0.107639,0.012029,10
4,0.221247,0.012318,0.017221,0.001228,100,linear,"{'C': 100, 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,4
5,0.118598,0.007145,0.019543,0.002828,100,poly,"{'C': 100, 'kernel': 'poly'}",-0.132885,-0.082461,-0.129220,-0.139962,-0.189219,-0.134749,0.033948,14
6,0.133305,0.011335,0.058622,0.005925,100,rbf,"{'C': 100, 'kernel': 'rbf'}",-0.160182,-0.107253,-0.123430,-0.137753,-0.209551,-0.147634,0.035511,17
7,0.139320,0.004793,0.028166,0.000691,100,sigmoid,"{'C': 100, 'kernel': 'sigmoid'}",-0.142455,-0.160831,-0.117544,-0.137984,-0.130402,-0.137843,0.014263,15
8,0.712437,0.083053,0.017564,0.001087,1000,linear,"{'C': 1000, 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,1
9,0.128467,0.005800,0.016718,0.000834,1000,poly,"{'C': 1000, 'kernel': 'poly'}",-0.080527,-0.028469,-0.073376,-0.086611,-0.134493,-0.080695,0.033795,8
10,0.120627,0.015116,0.058830,0.008535,1000,rbf,"{'C': 1000, 'kernel': 'rbf'}",-0.155430,-0.098267,-0.123724,-0.137137,-0.206405,-0.144193,0.036262,16
11,0.148378,0.012633,0.028076,0.001723,1000,sigmoid,"{'C': 1000, 'kernel': 'sigmoid'}",-2.043140,-2.686121,-2.194563,-2.210858,-1.942521,-2.215441,0.255409,18
12,1.114412,0.063965,0.015521,0.000204,2000,linear,"{'C': 2000, 'kernel': 'linear'}",0.682349,0.630642,0.750714,0.646368,0.722261,0.686467,0.045056,2
13,0.151023,0.010765,0.016067,0.000404,2000,poly,"{'C': 2000, 'kernel': 'poly'}",-0.020567,0.035685,-0.011468,-0.024587,-0.076360,-0.019459,0.035693,7
14,0.120978,0.004190,0.049943,0.003396,2000,rbf,"{'C': 2000, 'kernel': 'rbf'}",-0.143510,-0.087595,-0.113312,-0.128591,-0.193992,-0.133400,0.035492,13
15,0.131106,0.013990,0.028274,0.003435,2000,sigmoid,"{'C': 2000, 'kernel': 'sigmoid'}",-7.209317,-9.282940,-7.776578,-7.745074,-6.891719,-7.781126,0.821557,19
16,1.810659,0.283590,0.011285,0.003036,3000,linear,"{'C': 3000, 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,3
17,0.169278,0.012895,0.016581,0.000518,3000,poly,"{'C': 3000, 'kernel': 'poly'}",0.037700,0.098496,0.049291,0.035615,-0.020924,0.040035,0.038064,5
18,0.119159,0.005159,0.053878,0.009104,3000,rbf,"{'C': 3000, 'kernel': 'rbf'}",-0.128958,-0.075578,-0.100199,-0.116051,-0.179304,-0.120018,0.034578,11
19,0.128175,0.013773,0.025818,0.001369,3000,sigmoid,"{'C': 3000, 'kernel': 'sigmoid'}",-15.561853,-20.498908,-17.095474,-16.750877,-15.012168,-16.983856,1.914783,20

In [36]:
age_input=float(input("Enter the age:"))
bmi_input=float(input("Enter the bmi:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
children_input=int(input("Enter the children:"))
smoker_yes_input=int(input("smoker yes 0 or 1"))

Enter the age: 38
Enter the bmi: 67
Sex Male 0 or 1: 1
Enter the children: 4
smoker yes 0 or 1 0

In [37]:
Future_prediction=grid.predict([[age_input,bmi_input,sex_male_input,children_input,smoker_yes_input]])# change the parameters
print("Future prediction={}".format(Future_prediction))

Future prediction=[6417.45804759]

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(