In [1]:
#XG Boosting Algorithm:
import xgboost

In [2]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\anaconda3\lib\site-packages (3.3.0)
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from xgboost) (1.16.3)

In [3]:
import xgboost as xgb

In [4]:
import pandas as pd

In [5]:
dataset=pd.read_csv("insurance_pre.csv")

In [6]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [7]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [8]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [9]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [10]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [11]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [12]:
dependent=dataset[["charges"]]

In [13]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [14]:
from sklearn.model_selection import GridSearchCV

param_grid= {'n_estimators':[10,50,100,1000]}

grid=GridSearchCV(xgb.XGBRegressor(),param_grid,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

GridSearchCV(estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=True, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, max_bin=None,
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1, param_grid={'n_estimators': [10, 50, 100, 1000]},
             verbose=3)

In [15]:
re=grid.cv_results_
re

{'mean_fit_time': array([0.03445106, 0.0559073 , 0.07849088, 0.62324061]),
 'std_fit_time': array([0.01617599, 0.01944207, 0.00323485, 0.01117972]),
 'mean_score_time': array([0.00803685, 0.00686841, 0.00631919, 0.01282272]),
 'std_score_time': array([0.00195715, 0.00057788, 0.00050338, 0.00140709]),
 'param_n_estimators': masked_array(data=[10, 50, 100, 1000],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'n_estimators': 10},
  {'n_estimators': 50},
  {'n_estimators': 100},
  {'n_estimators': 1000}],
 'split0_test_score': array([0.85673738, 0.82545912, 0.81060082, 0.79770017]),
 'split1_test_score': array([0.80044234, 0.7609266 , 0.74092877, 0.72211969]),
 'split2_test_score': array([0.87260789, 0.8478961 , 0.83106446, 0.81601661]),
 'split3_test_score': array([0.83935368, 0.82178807, 0.81463724, 0.80569416]),
 'split4_test_score': array([0.86391413, 0.84529388, 0.83346897, 0.82394731]),
 'mean_test_score': array([0.84661108, 0.82027276, 0.80614005, 0.79309559]),
 'std_test_score': array([0.0255421 , 0.03143331, 0.0338015 , 0.03659155]),
 'rank_test_score': array([1, 2, 3, 4], dtype=int32)}

In [17]:
print("The R_score of the best parameter={}".format(grid.best_params_))

The R_score of the best parameter={'n_estimators': 10}

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.034451,0.016176,0.008037,0.001957,10,{'n_estimators': 10},0.856737,0.800442,0.872608,0.839354,0.863914,0.846611,0.025542,1
1,0.055907,0.019442,0.006868,0.000578,50,{'n_estimators': 50},0.825459,0.760927,0.847896,0.821788,0.845294,0.820273,0.031433,2
2,0.078491,0.003235,0.006319,0.000503,100,{'n_estimators': 100},0.810601,0.740929,0.831064,0.814637,0.833469,0.806140,0.033802,3
3,0.623241,0.011180,0.012823,0.001407,1000,{'n_estimators': 1000},0.797700,0.722120,0.816017,0.805694,0.823947,0.793096,0.036592,4

In [20]:
age_input=float(input("Enter the age:"))
bmi_input=float(input("Enter the bmi:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
children_input=int(input("Enter the children:"))
smoker_yes_input=int(input("smoker yes 0 or 1"))

Enter the age: 45
Enter the bmi: 67
Sex Male 0 or 1: 1
Enter the children: 1
smoker yes 0 or 1 1

In [21]:
Future_prediction=grid.predict([[age_input,bmi_input,sex_male_input,children_input,smoker_yes_input]])

In [22]:
print("Future prediction={}".format(Future_prediction))

Future prediction=[50506.996]